# -*- coding: utf-8 -*-
"""bank_oop_python_account.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eo8bDCSTZaGgy0CJ39yMI3bJEC2lSUw0
"""

#tạo lớp con nguoi
class con_nguoi:
  def __init__(self,ten,tuoi,gioi_tinh,nghe_nghiep):
    self.ten = ten
    self.tuoi = tuoi
    self.gioi_tinh = gioi_tinh
    self.nghe_nghiep = nghe_nghiep
  #tạo hàm nghề nghiệp để khai báo nghề nghiệp
  def _nghe_nghiep(self):
    if self.tuoi <= 18:
      return "học sinh"
    elif 18 < self.tuoi < 25:
      return "sinh viên"
    else:
      if self.nghe_nghiep != "":
        return self.nghe_nghiep
      else:
        return "người đi làm"
  def hoat_dong(self):
    if self.tuoi < 25:
        return "học bài"
    else:
      return "làm việc"
#tạo lớp con bank_account
class bank_account(con_nguoi):
  def __init__(self,ten,tuoi,nghe_nghiep,gioi_tinh,so_tai_khoan,so_du):
    super().__init__(ten,tuoi,gioi_tinh,nghe_nghiep)
    self.__so_tai_khoan = so_tai_khoan
    self.__so_du = so_du
    print("tạo tài khoản thành công")
    print("  ---chào mừng")
  def id_account(self):
    return self.__so_tai_khoan
  def so_du(self):
    return self.__so_du
#đầu vào người dùng
ten_nguoi = input("nhập tên: ")  #nhập tên người dùng
tuoi_nguoi = int(input("nhập tuổi: ")) #nhập tuổi người dùng
gioi_tinh_nguoi = input("nhập giới tính: ") #nhập giới tính người dùng
nghe_nghiep_nguoi = input("nhập nghề nghiệp: ") #nhập nghề nghiệp người dùng, nếu nghề nghiệp bỏ trống thì xác định nghề theo độ tuổi
#tao thông tin nguoi dùng
my_account = con_nguoi(ten_nguoi,tuoi_nguoi,gioi_tinh_nguoi,nghe_nghiep_nguoi)
#tao tai khoan ngan hang
id_bank = input("nhập id tự tạo")
so_du_tai_khoan = input("nhập số dư tài khoản tùy chỉnh")
bank = bank_account(ten_nguoi,tuoi_nguoi,nghe_nghiep_nguoi,gioi_tinh_nguoi,id_bank,so_du_tai_khoan)